apiVersion: kubesentry.io/v1alpha1
kind: Policy
metadata:
  name: automount-service-account-token
  labels:
    kubesentry.io/category: security
    kubesentry.io/source: builtin
spec:
  match:
    operations: [CREATE, UPDATE]
    resources:
      - apiGroups: [""]
        apiVersions: [v1]
        resources: [pods, serviceaccounts]
  enforcementMode: audit
  description: "Fails when automountServiceAccountToken is not explicitly set to false."
  rego: |
    package kubesentry

    deny[msg] {
      input.request.resource.resource == "pods"
      not input.request.object.spec.automountServiceAccountToken == false
      msg := "Pod should set spec.automountServiceAccountToken=false"
    }
    deny[msg] {
      input.request.resource.resource == "serviceaccounts"
      not input.request.object.automountServiceAccountToken == false
      msg := sprintf("ServiceAccount %q should set automountServiceAccountToken=false", [input.request.object.metadata.name])
    }
