apiVersion: kubesentry.io/v1alpha1
kind: Policy
metadata:
  name: host-ipc-set
  labels:
    kubesentry.io/category: security
    kubesentry.io/source: builtin
spec:
  match:
    operations: [CREATE, UPDATE]
    resources:
      - apiGroups: [""]
        apiVersions: [v1]
        resources: [pods]
      - apiGroups: [apps]
        apiVersions: [v1]
        resources: [deployments, statefulsets, daemonsets]
  enforcementMode: enforce
  description: "Fails when hostIPC attribute is configured."
  rego: |
    package kubesentry

    _spec(obj) = obj.spec {
      input.request.resource.resource == "pods"
    }
    _spec(obj) = obj.spec.template.spec {
      input.request.resource.resource != "pods"
    }

    deny[msg] {
      spec := _spec(input.request.object)
      spec.hostIPC == true
      msg := "hostIPC must not be set"
    }
