apiVersion: kubesentry.io/v1alpha1
kind: Policy
metadata:
  name: host-network-set
  labels:
    kubesentry.io/category: security
    kubesentry.io/source: builtin
spec:
  match:
    operations: [CREATE, UPDATE]
    resources:
      - apiGroups: [""]
        apiVersions: [v1]
        resources: [pods]
  enforcementMode: audit
  description: "Fails when hostNetwork attribute is configured."
  rego: |
    package kubesentry

    deny[msg] {
      input.request.object.spec.hostNetwork == true
      msg := "hostNetwork must not be set"
    }
