apiVersion: kubesentry.io/v1alpha1
kind: Policy
metadata:
  name: host-port-set
  labels:
    kubesentry.io/category: security
    kubesentry.io/source: builtin
spec:
  match:
    operations: [CREATE, UPDATE]
    resources:
      - apiGroups: [""]
        apiVersions: [v1]
        resources: [pods]
  enforcementMode: audit
  description: "Fails when hostPort attribute is configured."
  rego: |
    package kubesentry

    deny[msg] {
      c := input.request.object.spec.containers[_]
      port := c.ports[_]
      port.hostPort > 0
      msg := sprintf("container %q must not set hostPort %d", [c.name, port.hostPort])
    }
