apiVersion: kubesentry.io/v1alpha1
kind: Policy
metadata:
  name: memory-requests-missing
  labels:
    kubesentry.io/category: efficiency
    kubesentry.io/source: builtin
spec:
  match:
    operations: [CREATE, UPDATE]
    resources:
      - apiGroups: [""]
        apiVersions: [v1]
        resources: [pods]
      - apiGroups: [apps]
        apiVersions: [v1]
        resources: [deployments, statefulsets, daemonsets]
      - apiGroups: [batch]
        apiVersions: [v1]
        resources: [jobs, cronjobs]
  enforcementMode: audit
  description: "Fails when resources.requests.memory is not configured."
  rego: |
    package kubesentry

    _containers[c] {
      input.request.resource.resource == "pods"
      c := input.request.object.spec.containers[_]
    }
    _containers[c] {
      r := input.request.resource.resource
      r != "pods"
      r != "cronjobs"
      c := input.request.object.spec.template.spec.containers[_]
    }
    _containers[c] {
      input.request.resource.resource == "cronjobs"
      c := input.request.object.spec.jobTemplate.spec.template.spec.containers[_]
    }

    deny[msg] {
      c := _containers[_]
      not c.resources.requests.memory
      msg := sprintf("container %q must set resources.requests.memory", [c.name])
    }
