apiVersion: kubesentry.io/v1alpha1
kind: Policy
metadata:
  name: priority-class-not-set
  labels:
    kubesentry.io/category: reliability
    kubesentry.io/source: builtin
spec:
  match:
    operations: [CREATE, UPDATE]
    resources:
      - apiGroups: [""]
        apiVersions: [v1]
        resources: [pods]
  enforcementMode: audit
  description: "Fails when priorityClassName is not set."
  rego: |
    package kubesentry

    deny[msg] {
      not input.request.object.spec.priorityClassName
      msg := "priorityClassName should be set"
    }
