apiVersion: kubesentry.io/v1alpha1
kind: Policy
metadata:
  name: pull-policy-not-always
  labels:
    kubesentry.io/category: reliability
    kubesentry.io/source: builtin
spec:
  match:
    operations: [CREATE, UPDATE]
    resources:
      - apiGroups: [""]
        apiVersions: [v1]
        resources: [pods]
  enforcementMode: audit
  description: "Fails when imagePullPolicy is not Always."
  rego: |
    package kubesentry

    deny[msg] {
      c := input.request.object.spec.containers[_]
      c.imagePullPolicy != "Always"
      msg := sprintf("container %q imagePullPolicy should be Always, got %q", [c.name, c.imagePullPolicy])
    }
