apiVersion: kubesentry.io/v1alpha1
kind: Policy
metadata:
  name: run-as-root-allowed
  labels:
    kubesentry.io/category: security
    kubesentry.io/source: builtin
spec:
  match:
    operations: [CREATE, UPDATE]
    resources:
      - apiGroups: [""]
        apiVersions: [v1]
        resources: [pods]
  enforcementMode: audit
  description: "Fails when securityContext.runAsNonRoot is not true."
  rego: |
    package kubesentry

    deny[msg] {
      c := input.request.object.spec.containers[_]
      not c.securityContext.runAsNonRoot == true
      msg := sprintf("container %q should set securityContext.runAsNonRoot=true", [c.name])
    }
    deny[msg] {
      c := input.request.object.spec.initContainers[_]
      not c.securityContext.runAsNonRoot == true
      msg := sprintf("initContainer %q should set securityContext.runAsNonRoot=true", [c.name])
    }
