apiVersion: kubesentry.io/v1alpha1
kind: Policy
metadata:
  name: topology-spread-constraint
  labels:
    kubesentry.io/category: reliability
    kubesentry.io/source: builtin
spec:
  match:
    operations: [CREATE, UPDATE]
    resources:
      - apiGroups: [""]
        apiVersions: [v1]
        resources: [pods]
      - apiGroups: [apps]
        apiVersions: [v1]
        resources: [deployments, statefulsets]
  enforcementMode: audit
  description: "Fails when no topology spread constraint is defined."
  rego: |
    package kubesentry

    _spec(obj) = obj.spec {
      input.request.resource.resource == "pods"
    }
    _spec(obj) = obj.spec.template.spec {
      input.request.resource.resource != "pods"
    }

    deny[msg] {
      spec := _spec(input.request.object)
      not spec.topologySpreadConstraints
      msg := "no topologySpreadConstraints defined"
    }
    deny[msg] {
      spec := _spec(input.request.object)
      count(spec.topologySpreadConstraints) == 0
      msg := "topologySpreadConstraints is empty"
    }
