{{- range $groupName, $group := .Values.builtinGroups }}
---
apiVersion: kubesentry.io/v1alpha1
kind: PolicyGroup
metadata:
  name: {{ $groupName }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  displayName: {{ $group.displayName | quote }}
  description: {{ $group.description | default "" | quote }}
  enabled: {{ $group.enabled }}
  policies:
  {{- range $key, $policy := $group.policies }}
    - key: {{ $key }}
      {{- if hasKey $policy "enabled" }}
      enabled: {{ $policy.enabled }}
      {{- end }}
      {{- if $policy.mode }}
      mode: {{ $policy.mode | quote }}
      {{- end }}
      {{- if $policy.rego }}
      rego: |
        {{ $policy.rego | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
