apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesentry-webhook
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesentry-operator
  namespace: {{ .Values.namespace }}
