metadata:
  name: security
spec:
  displayName: "Security"
  description: "Security policies for Kubernetes workloads"
  members:
    - run-as-privileged
    - privilege-escalation-allowed
    - run-as-root-allowed
    - not-read-only-root-filesystem
    - linux-hardening
    - insecure-capabilities
    - dangerous-capabilities
    - host-pid-set
    - host-ipc-set
    - host-network-set
    - host-port-set
    - sensitive-container-env-var
    - automount-service-account-token
    - sensitive-configmap-content
    - tls-settings-missing
    - clusterrole-pod-exec-attach
    - role-pod-exec-attach
    - clusterrolebinding-pod-exec-attach
    - rolebinding-role-pod-exec-attach
    - rolebinding-cluster-role-pod-exec-attach
    - clusterrolebinding-cluster-admin
    - rolebinding-cluster-admin-cluster-role
    - rolebinding-cluster-admin-role
