apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubesentry-operator
rules:
  - apiGroups: [kubesentry.io]
    resources: [policies, policies/status, policyversions, policygroups, policygroups/status]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations]
    verbs: [get, list, watch, patch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: ["coordination.k8s.io"]
    resources: [leases]
    verbs: [get, create, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubesentry-operator
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: [secrets]
    resourceNames: [{{ .Values.tls.secretName }}]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubesentry-operator
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubesentry-operator
subjects:
  - kind: ServiceAccount
    name: kubesentry-operator
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubesentry-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubesentry-operator
subjects:
  - kind: ServiceAccount
    name: kubesentry-operator
    namespace: {{ .Values.namespace }}
