//go:build !ignore_autogenerated

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *PolicyExceptionMatch) DeepCopyInto(out *PolicyExceptionMatch) {
	*out = *in
	if in.Namespaces != nil {
		out.Namespaces = make([]string, len(in.Namespaces))
		copy(out.Namespaces, in.Namespaces)
	}
	if in.NamespaceSelector != nil {
		out.NamespaceSelector = in.NamespaceSelector.DeepCopy()
	}
	if in.ResourceSelector != nil {
		out.ResourceSelector = in.ResourceSelector.DeepCopy()
	}
}

func (in *PolicyExceptionSpec) DeepCopyInto(out *PolicyExceptionSpec) {
	*out = *in
	if in.PolicyRefs != nil {
		out.PolicyRefs = make([]string, len(in.PolicyRefs))
		copy(out.PolicyRefs, in.PolicyRefs)
	}
	if in.PolicyGroupRefs != nil {
		out.PolicyGroupRefs = make([]string, len(in.PolicyGroupRefs))
		copy(out.PolicyGroupRefs, in.PolicyGroupRefs)
	}
	in.Match.DeepCopyInto(&out.Match)
}

func (in *PolicyExceptionStatus) DeepCopyInto(out *PolicyExceptionStatus) {
	*out = *in
	if in.EffectiveAt != nil {
		t := in.EffectiveAt.DeepCopy()
		out.EffectiveAt = t
	}
	if in.ExpiresAt != nil {
		t := in.ExpiresAt.DeepCopy()
		out.ExpiresAt = t
	}
}

func (in *PolicyException) DeepCopyInto(out *PolicyException) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PolicyException) DeepCopy() *PolicyException {
	if in == nil {
		return nil
	}
	out := new(PolicyException)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyException) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PolicyExceptionList) DeepCopyInto(out *PolicyExceptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PolicyException, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *PolicyExceptionList) DeepCopy() *PolicyExceptionList {
	if in == nil {
		return nil
	}
	out := new(PolicyExceptionList)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyExceptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
