//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *MatchResource) DeepCopyInto(out *MatchResource) {
	*out = *in
	if in.APIGroups != nil {
		out.APIGroups = make([]string, len(in.APIGroups))
		copy(out.APIGroups, in.APIGroups)
	}
	if in.APIVersions != nil {
		out.APIVersions = make([]string, len(in.APIVersions))
		copy(out.APIVersions, in.APIVersions)
	}
	if in.Resources != nil {
		out.Resources = make([]string, len(in.Resources))
		copy(out.Resources, in.Resources)
	}
}

func (in *PolicyMatch) DeepCopyInto(out *PolicyMatch) {
	*out = *in
	if in.Operations != nil {
		out.Operations = make([]string, len(in.Operations))
		copy(out.Operations, in.Operations)
	}
	if in.Resources != nil {
		out.Resources = make([]MatchResource, len(in.Resources))
		for i := range in.Resources {
			in.Resources[i].DeepCopyInto(&out.Resources[i])
		}
	}
	if in.NamespaceSelector != nil {
		out.NamespaceSelector = in.NamespaceSelector.DeepCopy()
	}
}

func (in *RollbackTo) DeepCopy() *RollbackTo {
	if in == nil {
		return nil
	}
	return &RollbackTo{Version: in.Version}
}

func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	out.RollbackTo = in.RollbackTo.DeepCopy()
}

func (in *PolicyVersionSummary) DeepCopyInto(out *PolicyVersionSummary) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		t := in.LastSyncTime.DeepCopy()
		out.LastSyncTime = t
	}
	if in.VersionHistory != nil {
		out.VersionHistory = make([]PolicyVersionSummary, len(in.VersionHistory))
		for i := range in.VersionHistory {
			in.VersionHistory[i].DeepCopyInto(&out.VersionHistory[i])
		}
	}
}

func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

func (in *Policy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PolicyList) DeepCopyInto(out *PolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Policy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *PolicyList) DeepCopy() *PolicyList {
	if in == nil {
		return nil
	}
	out := new(PolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PolicyVersionSpec) DeepCopyInto(out *PolicyVersionSpec) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

func (in *PolicyVersion) DeepCopyInto(out *PolicyVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *PolicyVersion) DeepCopy() *PolicyVersion {
	if in == nil {
		return nil
	}
	out := new(PolicyVersion)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PolicyVersionList) DeepCopyInto(out *PolicyVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PolicyVersion, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *PolicyVersionList) DeepCopy() *PolicyVersionList {
	if in == nil {
		return nil
	}
	out := new(PolicyVersionList)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
