{{- if .Values.console.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesentry-console
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.console.replicas }}
  selector:
    matchLabels:
      app: kubesentry-console
  template:
    metadata:
      labels:
        app: kubesentry-console
    spec:
      serviceAccountName: kubesentry-console
      containers:
        - name: console
          image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          resources:
            {{- toYaml .Values.console.resources | nindent 12 }}
{{- end }}
