apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubesentry-tls-setup
rules:
  - apiGroups: [""]
    resources: [secrets]
    resourceNames: [{{ .Values.tls.secretName }}]
    verbs: [get, create, update]
  - apiGroups: [admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations]
    resourceNames: [kubesentry]
    verbs: [get, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubesentry-tls-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubesentry-tls-setup
subjects:
  - kind: ServiceAccount
    name: kubesentry-tls-setup
    namespace: {{ .Values.namespace }}
